[package]
name = "navix-client"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
cargo = "0.97.1"
chrono = "0.4.45"
rustls = "0.23.40"
serde = "1.0.228"
serde_json = "1.0.150"
tokio = { version = "1.52.3", features = [ "full" ] } 
webpki-roots = "1.0.7"
zbus = "5.16.0"
zbus_systemd = { version = "0.26000.0", features = ["systemd1"] }
